language: php

php:
  - 5.5
  - 5.6
  - 7.0

sudo: false

env:
  - DB=mysql db_dsn='mysql://travis@0.0.0.0/cakephp_test'
  - DB=pgsql db_dsn='postgres://travis@127.0.0.1/cakephp_test'
  - DB=sqlite

matrix:
  fast_finish: true
  include:
    - php: 7.0
    - php: 5.5
      env: PREFER_LOWEST=1

install:
  - composer self-update
  - sh -c "if [ '$PREFER_LOWEST' != '1' ]; then composer install --prefer-dist --no-interaction; fi"
  - sh -c "if [ '$PREFER_LOWEST' = '1' ]; then composer update --prefer-dist --no-interaction --prefer-lowest --prefer-stable; fi"

before_script:
  - sh -c "if [ '$DB' = 'mysql' ]; then mysql -e 'CREATE DATABASE cakephp_test;'; fi"
  - sh -c "if [ '$DB' = 'pgsql' ]; then psql -c 'CREATE DATABASE cakephp_test;' -U postgres; fi"
  - phpenv rehash
  - set +H

script:
  - vendor/bin/phpunit

notifications:
  email: false
