language: php

php:
  - 5.5
  - 5.6
  - 7.0

sudo: false

env:
  - DB=mysql db_dsn='mysql://travis@0.0.0.0/cakephp_test'
  - DB=pgsql db_dsn='postgres://travis@127.0.0.1/cakephp_test'
  - DB=sqlite

matrix:
  fast_finish: true
  include:
    - php: 5.5
      env: PREFER_LOWEST=1
    - php: 7.0
      env: COVERAGE=1

install:
  - composer self-update
  - if [[ $PREFER_LOWEST != 1 ]]; then composer install --prefer-dist --no-interaction; fi
  - if [[ $PREFER_LOWEST == 1 ]]; then composer update --prefer-dist --no-interaction --prefer-lowest --prefer-stable; fi

before_script:
  - if [[ $DB == 'mysql' ]]; then mysql -e 'CREATE DATABASE cakephp_test;'; fi
  - if [[ $DB == 'pgsql' ]]; then psql -c 'CREATE DATABASE cakephp_test;' -U postgres; fi
  - phpenv rehash
  - set +H

script:
  - if [[ $COVERAGE == 1 ]]; then phpdbg -qrr vendor/bin/phpunit --coverage-clover=coverage.xml; fi
  - if [[ $COVERAGE != 1 ]]; then vendor/bin/phpunit; fi

after_success:
  - if [[ $COVERAGE == 1 ]]; then bash <(curl -s https://codecov.io/bash); fi

notifications:
  email: false
